raw_dataset_dir: data/raw/
raw_dataset_path: data/processed/data.pkl
int32_columns:
- Year
float32_columns:
- NA_Sales
- EU_Sales
- JP_Sales
- Other_Sales
- Global_Sales
object_columns:
- Name
- Platform
- Genre
- Publisher
label: Global_Sales
predictors:
- Name
- Year
- Platform
- Genre
- Publisher
- NA_Sales
- EU_Sales
- JP_Sales
- Other_Sales
range_Year:
- -1
- 2020
range_NA_Sales:
- 0
- 999
range_EU_Sales:
- 0
- 999
range_JP_Sales:
- 0
- 999
range_Other_Sales:
- 0
- 999
range_Global_Sales:
- 0 
- 999
