# path related
raw_dataset_dir: data/raw/
raw_dataset_path: data/processed/raw_data.pkl
cleaned_raw_dataset_path: data/processed/cleaned_raw_data.pkl
train_set_path:
- data/processed/X_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/X_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/X_test.pkl
- data/processed/y_test.pkl
train_feng_set_path: data/processed/X_train_feng.pkl
valid_feng_set_path: data/processed/X_valid_feng.pkl
test_feng_set_path: data/processed/X_test_feng.pkl
training_log_path: log/training_log.json

# debug related
print_debug: true

# columns features
cols_drop:
- Rank
- Name
- Platform
- Year
- Genre
- Publisher
float32_columns:
- NA_Sales
- EU_Sales
- JP_Sales
- Other_Sales
- Global_Sales
predictors:
- NA_Sales
- EU_Sales
- JP_Sales
- Other_Sales
label: Global_Sales

# range of data
range_NA_Sales:
- 0
- 999
range_EU_Sales:
- 0
- 999
range_JP_Sales:
- 0
- 999
range_Other_Sales:
- 0
- 999
range_Global_Sales:
- 0 
- 999
